kind: Namespace
apiVersion: v1
metadata:
  name: myapp
  labels:
    name: test

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deploy
  namespace: myapp
spec:
  minReadySeconds: 5
  replicas: 4
  selector:
    matchLabels: 
      app: spc
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels: 
        app: spc

    spec:
      containers: 
        - image:  sadik8143/springclinic:46
          name: webcont
          resources: 
            limits:
              cpu: 500m
              memory: 256M
            requests:
              cpu: 100m
              memory: 64M
          ports:
            - containerPort: 8080

          livenessProbe: 
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe: 
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10         

---
apiVersion: v1
kind: Service
metadata:
  namespace: myapp
  name: spring-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  
spec:
  selector:
    app: spc
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080






      